[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo

server_wide_modules = base,web,base_setup

admin_passwd = @@zencore+masterPassword@$#

db_host = db
db_port = 5432
db_user = odoo

db_maxconn = 8
list_db = True

without_demo = all
workers = 2
max_cron_threads = 1

limit_memory_soft = 536870912
limit_memory_hard = 805306368
limit_time_cpu    = 60
limit_time_real   = 120
limit_request     = 8192

gevent_port = 8072

proxy_mode = False

; ── Logging ──────────────────────────────────────────────────────────────────
logfile = /var/log/odoo/odoo.log
log_level = info
log_handler = :INFO

; ── Misc ─────────────────────────────────────────────────────────────────────
csv_internal_sep = ,
unaccent = False

