[options]
admin_passwd = AdminMasterPassword
db_host = postgres_prod
db_port = 5432
db_user = odoo
db_password = StrongProdPassword
addons_path = /mnt/extra-addons
logfile = /var/log/odoo/odoo.log
log_level = info
data_dir = /var/lib/odoo